syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
option csharp_namespace = "Discount.Grpc";

package discount;

// The discount service definition.
service DiscountProtoService {

  //Discount CRUD opérations
  rpc GetDiscount (GetDiscountRequest) returns (CouponModel) {
    option (google.api.http) = {
      get: "/discounts/{product_name}"
    };
  };
  rpc CreateDiscount (CreateDiscountRequest) returns (CouponModel) {
    option (google.api.http) = {
      post: "/discounts",
      body: "coupon"
    };
  };
  rpc UpdateDiscount (UpdateDiscountRequest) returns (CouponModel) {
    option (google.api.http) = {
      put: "/discounts/{coupon.id}",
      body: "coupon"
    };
  };
  rpc DeleteDiscount (DeleteDiscountRequest) returns (DeleteDiscountResponse) {
    option (google.api.http) = {
      delete: "/discounts/{id}"
    };
  };

}

message GetDiscountRequest {
  string product_name = 1;
  optional string code = 2;
}

message CouponModel {
  int32 id = 1;
  string product_name = 2;
  string description = 3;
  string code = 4;
  enum CouponDiscountType {
    Amount = 0;
    Percentage = 1;
  }
  CouponDiscountType discount_type = 5;
  optional double max_percentage_cap = 6;
  optional string category = 7;
  optional google.protobuf.Timestamp starts_at = 8;
  optional google.protobuf.Timestamp expires_at = 9;
  bool is_active = 10;
  oneof value {
    int64 amount_in_minor = 11;
    int32 percentage_bps = 12;
  }
}

message CreateDiscountRequest {
  CouponModel coupon = 1;
}

message UpdateDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountRequest {
  int32 id = 1;
}

message DeleteDiscountResponse {
  bool success = 1;
}
