// <auto-generated />
using Discount.Grpc.Data;
using Discount.Grpc.Models.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowStacking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoApply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FixedAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxStackPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowStacking = false,
                            AutoApply = true,
                            Category = "",
                            Code = "",
                            Description = "Back to school 10%",
                            EndDate = new DateTimeOffset(new DateTime(2024, 4, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            FixedAmount = 0m,
                            IsDisabled = false,
                            MaxStackPercentage = 0.30m,
                            MinimumAmount = 0m,
                            Percentage = 0.10m,
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductName = "IPhone 15 Pro",
                            StartDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            Status = (int)DiscountStatus.Active,
                            Type = (int)DiscountType.Percentage
                        },
                        new
                        {
                            Id = 2,
                            AllowStacking = true,
                            AutoApply = true,
                            Category = "Electronics",
                            Code = "",
                            Description = "Electronics seasonal sale",
                            EndDate = new DateTimeOffset(new DateTime(2024, 2, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            FixedAmount = 0m,
                            IsDisabled = false,
                            MaxStackPercentage = 0.30m,
                            MinimumAmount = 100m,
                            Percentage = 0m,
                            ProductId = null,
                            ProductName = "",
                            StartDate = new DateTimeOffset(new DateTime(2023, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            Status = (int)DiscountStatus.Active,
                            Type = (int)DiscountType.Percentage
                        },
                        new
                        {
                            Id = 3,
                            AllowStacking = true,
                            AutoApply = false,
                            Category = "",
                            Code = "SUMMER2024",
                            Description = "Summer code 10% + 5€",
                            EndDate = new DateTimeOffset(new DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            FixedAmount = 5m,
                            IsDisabled = false,
                            MaxStackPercentage = 0.30m,
                            MinimumAmount = 50m,
                            Percentage = 0.10m,
                            ProductId = null,
                            ProductName = "",
                            StartDate = new DateTimeOffset(new DateTime(2023, 12, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            Status = (int)DiscountStatus.Active,
                            Type = (int)DiscountType.PercentagePlusFixedAmount
                        },
                        new
                        {
                            Id = 4,
                            AllowStacking = false,
                            AutoApply = true,
                            Category = "Home",
                            Code = "",
                            Description = "Future home discount",
                            EndDate = new DateTimeOffset(new DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            FixedAmount = 0m,
                            IsDisabled = false,
                            MaxStackPercentage = 0.30m,
                            MinimumAmount = 0m,
                            Percentage = 0.15m,
                            ProductId = null,
                            ProductName = "",
                            StartDate = new DateTimeOffset(new DateTime(2024, 2, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0L)),
                            Status = (int)DiscountStatus.Upcoming,
                            Type = (int)DiscountType.Percentage
                        });
                });

            modelBuilder.Entity("Discount.Grpc.Models.DiscountTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FixedAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThresholdAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.ToTable("DiscountTier", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponId = 2,
                            FixedAmount = 0m,
                            Percentage = 0.05m,
                            ThresholdAmount = 100m
                        },
                        new
                        {
                            Id = 2,
                            CouponId = 2,
                            FixedAmount = 0m,
                            Percentage = 0.10m,
                            ThresholdAmount = 200m
                        });
                });

            modelBuilder.Entity("Discount.Grpc.Models.DiscountTier", b =>
                {
                    b.HasOne("Discount.Grpc.Models.Coupon", "Coupon")
                        .WithMany("Tiers")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
